name: macOS build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

concurrency:
  group: macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-macOS:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.python-version }})
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: ["macOS-latest"]
        python-version: ["3.9"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install GDAL
        run: brew install gdal
      - name: Test GDAL installation
        run: gdalinfo --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir Cython
          pip install -r requirements.txt
          pip install .
