name: pypi

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write    # required for OIDC to PyPI

concurrency:
  group: pypi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi   # using this env with required reviewers
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
