name: Linux build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  py-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.py }})
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, py: "3.9" }
          - { os: ubuntu-latest, py: "3.10" }
          - { os: ubuntu-latest, py: "3.11" }
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.config.py }}
      - name: Install GDAL
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir Cython
          pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
      - name: Test GDAL installation
        run: |
          python -c "from osgeo import gdal"
          gdalinfo --version
      - name: Install dependencies
        run: |
          pip install --user -r requirements.txt
          pip install .
      - name: Install pydot
        run: pip install pydot
      - name: Install graphviz
        run: sudo apt-get install -y graphviz
      - name: Install pytest
        run: pip install pytest
      - name: PKG-TEST
        run: pytest -v -s tests/
